### ISSUE TITLE
Suspicious condition in send_cmd

### ISSUE THREAD

**Issue by dikdom** [feilipu/z88dk-libraries#3]
Hello,
I'm still struggling to initialize my SD card, but during debug I found this in the `send_cmd() @ diskio_sd/source/diskio_sd.c `
```
[...]
    if (cmd != CMD0 || cmd != CMD12) {          /* Long wait for ready except to to initialise or stop multiple block read */
        wait_ready(true);                       /* Wait while SD busy (0x00 signal) */
    }
[...]
```
Is it truly you wanted? (it always enters to the block as the condition renders true)
(issue2: typo in the comment)

**Comment by feilipu** [comment]
This is the standard method to check for ready before issuing a new command. The SD card should return `0xFF` if it is ready, and will produce `0x00` if it is not ready to receive a command. See [here in the Arduino SD FAT library](https://github.com/greiman/SdFat/blob/master/src/SdCard/SdSpiCard.cpp#L245), for example of similar code.

Note that the SPI interface `MISO` line could (optionally) be pulled high with a 10k resistor, in case the SD Card doesn't feel it is being selected and therefore doesn't respond by holding the `MISO` high before `CMD0` is issued. This is not formally necessary, but is a useful practice. Wayne explains further in his [RomWBW implementation here](https://github.com/wwarthen/RomWBW/blob/master/Source/HBIOS/sd.asm#L84).


BTW. Thanks for noting the typo.

**Comment by dikdom** [comment]
Hello,
I meant this is always true: ```(cmd != CMD0 || cmd != CMD12)```
According to the comment ("Long wait for ready except to initialise or to stop multiple block read */") the condition should  be something like this:
```(cmd != CMD0 && cmd != CMD12)```
It might be that the comment is wrong or I miss something here...


ps: I'm reading the SD card on my custom ZX81 cartridge!

**Comment by feilipu** [comment]
> the condition should be something like this:
`(cmd != CMD0 && cmd != CMD12)`.

Ah yes. Sorry about being slow. You're quite right, and I'll fix it soonest.

__EDIT__ Found another small fix that was needed too. Thanks.
