### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by dikdom** [feilipu/z88dk-libraries#4]
Dear Feilipu,
I managed to fit the required SD handling routines into the ZX81 using my cart (requires bank switched EEPROM and 32k RAM).
I really appreciate your support and the code you provided. I created a small easter egg (?) in the menu handling with a credits. The English is not my native language, could you please check if that few lines of credits is OK for you? 

![IMG_20231026_190451_HDR](https://github.com/feilipu/z88dk-libraries/assets/28545061/f2446b48-7e85-4727-853b-a4440df60d2e)

I know you're interested so I can brag about how I managed to do it.. :) (it'll be short - basically I did what you suggested)
- I'm using the SJASM compiler, not the z88dk because of historical reasons
- I compiled a dummy ff program to ZX81 (I kept asm source) and converted to be compatible with SJASM
- I had to get the source of all the linked built-in z88dk helper routines also
- I had to workaround all the IX and IY register usage, because in stock ZX81 they are used in NMI (z88dk uses its own display routine - without IY - or IX - I don't remember now..)
- I split the source (compiled to around 12kB and 10 kB). 
- The first 1k is original ROM, so I didn't have to write a new display and keyboard routine set
- One of the blocks is copied to the ZX81 $4000-$7FFF area as code could be executed only from that RAM area, the other one stayed in ROM (one of the EEPROM BANK)
- References to SD handling routines are carefully fixed
- Loading a program is done into $8000-$BFFF area, then it is simply copied to its proper place: starting from $4009. And then banking back to the full ZX81 ROM and executed.

That's it. :)

**Comment by feilipu** [comment]
That will do nicely, thank you. Glad I could help.

It would be worth mentioning your game cart on the z88dk forums, where you'll find interested players.

**Comment by dikdom** [comment]
I thank you for your help! :)
